from typing import Protocol, runtime_checkable

from proxyscope.adapters.tui.components.contracts import ComponentFocus
from proxyscope.adapters.tui.models import DetailTab, RuntimeScreenModel, RuntimeView
from proxyscope.application.contracts import RequestPolicyAction, RequestPolicyTarget, SuspendUI
from proxyscope.application.shortcuts import ShortcutRegistry


@runtime_checkable
class RuntimeUIController(Protocol):
    @property
    def should_exit(self) -> bool: ...

    @property
    def shortcut_registry(self) -> ShortcutRegistry: ...

    def build_screen_model(self) -> RuntimeScreenModel: ...

    def execute_command(self, command: str) -> bool: ...

    def execute_shortcut_command(self, command: str) -> str | None: ...

    def is_help_command(self, command: str) -> bool: ...

    def build_help_text(self) -> str: ...

    def set_active_focus(self, focus: ComponentFocus) -> None: ...

    def switch_view(self, view: RuntimeView) -> None: ...

    def select_request(self, cursor: int) -> None: ...

    def toggle_request_follow_top(self) -> None: ...

    def open_selected_request_detail(self) -> None: ...

    def select_detail_tab(self, tab: DetailTab) -> None: ...

    def toggle_detail_ratio(self) -> None: ...

    def select_aux_tab(self, tab_key: str) -> None: ...

    def select_aux_item(self, cursor: int) -> None: ...

    def go_back(self) -> None: ...

    def add_selected_site_to_whitelist(self) -> None: ...

    def remove_selected_site_from_whitelist(self) -> None: ...

    def enable_selected_policy(self) -> None: ...

    def disable_selected_policy(self) -> None: ...

    def remove_selected_policy(self) -> None: ...

    def edit_selected_policy(self, *, suspend_ui: SuspendUI | None = None) -> None: ...

    def add_selected_request_to_editor_policy(self, *, suspend_ui: SuspendUI | None = None) -> None: ...

    def selected_request_has_response(self) -> bool: ...

    def apply_selected_request_policy_action(
        self,
        *,
        target: RequestPolicyTarget,
        action: RequestPolicyAction,
        suspend_ui: SuspendUI | None = None,
    ) -> None: ...

    def replay_selected_request(self, *, suspend_ui: SuspendUI | None = None) -> None: ...

    def process_pending_actions(self, *, suspend_ui: SuspendUI | None = None) -> None: ...
