"""Enforce branch coverage separately from coverage.py's combined percentage."""

import argparse
import json
from pathlib import Path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("report", type=Path, help="JSON report generated by coverage json")
    parser.add_argument("--minimum", type=float, default=81.0, help="Minimum branch percentage (default: 81)")
    args = parser.parse_args(argv)
    if not 0 <= args.minimum <= 100:
        parser.error("minimum must be between 0 and 100")
    totals = json.loads(args.report.read_text(encoding="utf-8"))["totals"]
    branches = totals.get("num_branches", 0)
    if branches <= 0:
        print("No branch coverage measured. Enable branch = true in the coverage configuration.")
        return 1
    covered = totals["covered_branches"]
    percentage = 100 * covered / branches
    print(f"Branch coverage: {percentage:.2f}% ({covered}/{branches}); required: {args.minimum:.2f}%")
    return 0 if percentage >= args.minimum else 1


if __name__ == "__main__":
    raise SystemExit(main())
