from typing import Protocol, runtime_checkable

from proxyscope.adapters.tui.models import ActivePane, DetailTab, RuntimeScreenModel
from proxyscope.application.contracts import SuspendUI


@runtime_checkable
class RuntimeUIController(Protocol):
    @property
    def should_exit(self) -> bool: ...

    def build_screen_model(self) -> RuntimeScreenModel: ...

    def execute_command(self, command: str) -> bool: ...

    def is_help_command(self, command: str) -> bool: ...

    def build_help_text(self) -> str: ...

    def set_status_message(self, message: str) -> None: ...

    def set_active_pane(self, pane: ActivePane) -> None: ...

    def select_request(self, cursor: int) -> None: ...

    def toggle_request_follow_top(self) -> None: ...

    def open_selected_request_detail(self) -> None: ...

    def select_detail_tab(self, tab: DetailTab) -> None: ...

    def select_aux_tab(self, tab_key: str) -> None: ...

    def select_aux_item(self, cursor: int) -> None: ...

    def toggle_aux_visibility(self) -> None: ...

    def go_back(self) -> None: ...

    def add_selected_site_to_whitelist(self) -> None: ...

    def remove_selected_site_from_whitelist(self) -> None: ...

    def enable_selected_policy(self) -> None: ...

    def disable_selected_policy(self) -> None: ...

    def remove_selected_policy(self) -> None: ...

    def edit_selected_policy(self, *, suspend_ui: SuspendUI | None = None) -> None: ...

    def add_selected_request_to_editor_policy(self, *, suspend_ui: SuspendUI | None = None) -> None: ...

    def replay_selected_request(self, *, suspend_ui: SuspendUI | None = None) -> None: ...

    def process_pending_actions(self, *, suspend_ui: SuspendUI | None = None) -> None: ...
